# Backlog Priorizado — Horta Familiar

| # | História | Critérios de aceite | Prioridade (MoSCoW) | Estimativa | Sprint alvo |
|---|---|---|---|---|---|
| 1 | Como usuário, quero criar minha conta e realizar login, para que eu possa acessar o sistema de acordo com meu perfil. | - E-mail deve ser único<br>- Senha deve atender aos requisitos mínimos definidos<br>- Sistema deve identificar o perfil do usuário<br>- Usuário não autenticado não pode acessar funcionalidades restritas | Must | 5 | Sprint 1 |
| 2 | Como administrador, quero cadastrar e gerenciar culturas, para que eu possa manter as informações das plantas cultivadas na horta. | - Campos obrigatórios devem ser validados<br>- Deve permitir informar nome da cultura, tempo médio de maturação e espaçamento ideal<br>- Não deve permitir cadastro duplicado da mesma cultura | Must | 3 | Sprint 1 |
| 3 | Como administrador, quero cadastrar e gerenciar canteiros, para que eu possa controlar os espaços disponíveis para plantio. | - Canteiro deve possuir identificação única<br>- Campos obrigatórios devem ser validados<br>- Não deve permitir identificação duplicada | Must | 3 | Sprint 1 |
| 4 | Como administrador, quero cadastrar e gerenciar insumos, para que eu possa controlar os recursos disponíveis na horta. | - Deve permitir cadastrar sementes, fertilizantes e ferramentas<br>- Deve registrar quantidade disponível e quantidade mínima de estoque<br>- Quantidade não pode ser negativa | Must | 5 | Sprint 1 |
| 5 | Como administrador, quero registrar um plantio relacionando uma cultura a um canteiro, para que eu possa acompanhar o desenvolvimento da produção. | - Deve relacionar uma cultura e um canteiro existentes<br>- Deve registrar a data do plantio<br>- Deve permitir informar o status do plantio<br>- Não deve permitir plantio sem cultura ou canteiro válido | Must | 5 | Sprint 2 |
| 6 | Como administrador, quero cadastrar e atribuir tarefas aos membros, para que as atividades da horta sejam organizadas. | - Tarefa deve possuir descrição, data e horário<br>- Deve permitir relacionar a tarefa a um canteiro e/ou insumo<br>- Deve permitir atribuir a tarefa a um membro<br>- Status da tarefa deve ser controlado pelo sistema | Must | 5 | Sprint 2 |
| 7 | Como membro, quero visualizar minhas tarefas, para que eu saiba quais atividades devo realizar. | - Exibe somente tarefas atribuídas ao usuário logado<br>- Exibe data, horário, descrição e local da tarefa<br>- Permite identificar tarefas pendentes e concluídas | Must | 3 | Sprint 2 |
| 8 | Como membro, quero registrar a realização de uma tarefa, para que o gestor tenha o histórico das atividades executadas. | - Usuário pode alterar o status da tarefa para concluída<br>- Sistema registra a data da conclusão<br>- Usuário não pode concluir tarefa atribuída a outro membro | Must | 3 | Sprint 2 |
| 9 | Como administrador, quero registrar a utilização de insumos em uma tarefa ou plantio, para que o estoque seja atualizado automaticamente. | - Deve registrar o insumo utilizado e a quantidade<br>- Quantidade utilizada não pode ser maior que o estoque disponível<br>- Após o registro, o estoque deve ser reduzido automaticamente<br>- A utilização deve ficar vinculada à tarefa ou plantio correspondente | Must | 8 | Sprint 3 |
| 10 | Como administrador, quero que o sistema valide a disponibilidade de insumos antes de agendar uma tarefa, para que não sejam planejadas atividades sem recursos suficientes. | - Sistema verifica o saldo disponível antes do agendamento<br>- Agendamento deve ser bloqueado quando o saldo for insuficiente<br>- Sistema deve informar claramente o motivo do bloqueio<br>- Situações de estoque abaixo do limite mínimo devem gerar alerta | Must | 5 | Sprint 3 |
| 11 | Como administrador, quero que o sistema identifique conflitos de recursos durante o agendamento, para que um mesmo canteiro ou ferramenta não seja utilizado em tarefas simultâneas. | - Sistema verifica tarefas existentes no mesmo período<br>- Deve identificar conflito de canteiro ou ferramenta<br>- Agendamento conflitante deve ser impedido<br>- Sistema deve informar qual recurso está ocupado | Must | 8 | Sprint 3 |
| 12 | Como administrador, quero visualizar um dashboard de produção, para que eu possa analisar o desempenho da horta e apoiar a tomada de decisões. | - Deve utilizar `JOIN` entre pelo menos 3 tabelas<br>- Deve utilizar `GROUP BY`<br>- Deve apresentar produtividade agrupada por cultura e canteiro<br>- Deve considerar o período definido para o relatório | Must | 8 | Sprint 4 |
| 13 | Como administrador, quero visualizar um resumo do estoque, para que eu identifique rapidamente os insumos disponíveis e os que precisam de reposição. | - Exibe quantidade atual dos insumos<br>- Destaca insumos abaixo do estoque mínimo<br>- Permite identificar quais insumos estão em situação de risco de ruptura | Should | 3 | Sprint 4 |
| 14 | Como administrador, quero aprovar uma tarefa que não possua estoque suficiente, para que situações excepcionais possam ser tratadas pelo responsável pela horta. | - Somente administrador pode aprovar a exceção<br>- Sistema deve registrar a aprovação<br>- A tarefa deve apresentar o status correspondente<br>- A aprovação não pode ocorrer sem confirmação do administrador | Could | 5 | Sprint 4 |
| 15 | Como administrador, quero exportar os dados do dashboard e estoque, para que eu possa utilizar os relatórios fora do sistema. | Fora de escopo neste semestre — a primeira versão disponibilizará os indicadores diretamente no dashboard. | Won't | — | — |
| 16 | Como usuário, quero utilizar um aplicativo mobile nativo, para que eu possa gerenciar a horta pelo celular. | Fora de escopo neste semestre — o MVP será desenvolvido como aplicação web. | Won't | — | — |
| 17 | Como gestor, quero receber notificações automáticas por e-mail sobre estoque e tarefas, para que eu não precise acessar o sistema para verificar alertas. | Fora de escopo neste semestre — os alertas serão apresentados dentro do sistema. | Won't | — | — |
